<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('SSF - Dashboard')->setSeparator(' - ')->setAutoEscape(false) ?>

    <!-- Custom meta tags -->
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Estilos globais -->
    <?= $this->headLink()
        ->prependStylesheet($this->basePath('css/style-global.css'))
        ->prependStylesheet($this->basePath('css/sb-admin-2.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet('https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i')
        ->prependStylesheet($this->basePath('vendor/fontawesome-free/css/all.min.css'))
    ?>

    <style>
        html, body {
            height: 100%;
            display: flex;
            justify-content: center;  /* Centraliza horizontalmente */
            align-items: center;      /* Centraliza verticalmente */
            text-align: center;       /* Garante que o texto fique centralizado */
            background-color: #f8f9fc; /* Ajuste conforme necessário */
        }

        .container-fluid {
            max-width: 600px; /* Define um limite para o conteúdo */
        }
        .error-404 { color: #e74a3b; }
        .error-500 { color: #f6c23e; }
        .error-other { color: #36b9cc; }
    </style>

    <!-- Scripts personalizados -->
    <?= $this->headScript() ?>
</head>

<?php 
    $erroCode = 404;
    $classeErro = 'error-other';
    // Verifique se a variável 'response' está definida
    if (isset($this->erro)) {
        $erroCode = $this->erro;
    } 

    if ($erroCode == 404) {
        $classeErro = 'error-404';
    } elseif ($erroCode == 500) {
        $classeErro = 'error-500';
    }
?>

<body>
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <!-- 404 Error Text -->
        <div class="text-center">
            <div class="error mx-auto <?php echo $classeErro; ?>" data-text="<?php echo $erroCode; ?>" data-text="<?php echo $erroCode  ?>"><?php echo $erroCode  ?></div>
            <p class="lead text-gray-800 mb-5">Página não encontrada</p>
            <p class="text-gray-500 mb-0">Parece que você encontrou uma falha na matriz...</p>
            <a href="/">&larr; Voltar para tela inicial</a>
        </div>
    </div>
</body>
</html>