
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('SSF - Dashboard')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Custom meta tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Favicon -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico']) ?>

    <!-- DevExtreme CSS (versão gratuita) -->
    <link rel="stylesheet" href="/devextreme/dist/css/dx.common.css">
    <link rel="stylesheet" href="/devextreme/dist/css/dx.light.css">

    <!-- Estilos globais -->
    <?= $this->headLink()
        ->prependStylesheet($this->basePath('css/style-global.css'))
        ->prependStylesheet($this->basePath('css/sb-admin-2.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet('https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i')
        ->prependStylesheet($this->basePath('vendor/fontawesome-free/css/all.min.css'))
    ?>

    <!-- jQuery (DevExtreme e Bootstrap dependem dele) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- DevExtreme Libraries -->
    <script src="/jszip/dist/jszip.min.js"></script>
    <script src="/devextreme/dist/js/dx.all.js"></script>

    <!-- CDN para localização em português -->
    <script src="/devextreme/dist/js/localization/dx.messages.pt.js"></script>
    

    <style>
        html, body {
            height: 100%;
            display: flex;
            justify-content: center;  /* Centraliza horizontalmente */
            align-items: center;      /* Centraliza verticalmente */
            text-align: center;       /* Garante que o texto fique centralizado */
            background-color: #f8f9fc; /* Ajuste conforme necessário */
        }

        .container-fluid {
            max-width: 600px; /* Define um limite para o conteúdo */
        }
    </style>

    <!-- Scripts personalizados -->
    <?= $this->headScript() ?>
</head>

<body>
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- 404 Error Text -->
        <div class="text-center">
            <div class="error mx-auto" data-text="403">403</div>
            <p class="lead text-gray-800 mb-5">Você não tem permissão para acessar essa tela.</p>
            <p class="text-gray-500 mb-0">Parece que você encontrou uma falha na matriz...</p>
            <a href="/">&larr; Voltar para tela inicial</a>
        </div>
    </div>
</body>
</html>