
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Gestão do Sistema</h1>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-12 mb-4">
            <!-- Approach -->
            <div class="card shadow mb-4">
                <div class="card-body">
                    <p>Cadastro de Departamentos</p>

                    <!-- Grid Container for the DataGrid -->
                    <div id="gridContainer"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->


<script>
    $(document).ready(function() {
        var usuariosDataSource = new DevExpress.data.CustomStore({
            key: "id_gestor_departamento",
            load: function(loadOptions) {
                return $.ajax({
                    url: '/departamento/get-lookup-gestor-departamento',
                    type: "GET",
                    dataType: "json",
                    data: { filtro: loadOptions.searchValue }
                }).then(function(data) {
                    return data;
                });
            },
            byKey: function(key) {
                return $.ajax({
                    url: '/departamento/get-lookup-gestor-departamento', 
                    type: "GET",
                    dataType: "json",
                    data: { id_gestor_departamento: key }
                }).then(function(data) {
                    var result = data.data;
                    return result.find(item => item.id_gestor_departamento == key);
                });
            }
        });


        let dataGrid = $('#gridContainer').dxDataGrid({
            dataSource: new DevExpress.data.CustomStore({
                key: 'id',
                loadMode: "processed",
                load: function(loadOptions) {
                    // Parâmetros para a requisição
                    let params = {
                        skip: loadOptions.skip || 0,
                        take: loadOptions.take || 500,
                        sort: loadOptions.sort ? JSON.stringify(loadOptions.sort) : null,
                    };

                    return $.ajax({
                        url: '/departamento/list-departamentos', // Endpoint para listar departamentos
                        method: 'GET',
                        dataType: 'json',
                        data: params,
                    }).then(response => {
                        if (response.success) {
                            return {
                                data: response.data,
                                totalCount: response.totalCount // Total de registros
                            };
                        } else {
                            DevExpress.ui.notify(response.message, "error", 3000);
                            return { data: [], totalCount: 0 };
                        }
                    }).catch(error => {
                        if (error.responseJSON) {
                            DevExpress.ui.notify(error.responseJSON.message, "error", 3000);
                            return { data: [], totalCount: 0 };
                        } else {
                            DevExpress.ui.notify("Erro ao buscar dados!", "error", 3000);
                            return { data: [], totalCount: 0 };
                        }
                    });
                },
                update: function(key, values) {
                    return $.ajax({
                        url: '/departamento/add-or-update-departamento', 
                        method: 'PUT',
                        contentType: 'application/json',
                        data: JSON.stringify({ id: key, ...values }),
                        dataType: 'json'
                    }).then(response => {
                        if (!response.success) {
                            DevExpress.ui.notify(response.message, "error", 3000);
                        } else {
                            DevExpress.ui.notify(response.message, "success", 2000);
                        }
                        return response;
                    }).catch(error => {
                        if (error.responseJSON) {
                            DevExpress.ui.notify(error.responseJSON.message, "error", 3000);
                            return {};
                        } else {
                            DevExpress.ui.notify("Erro ao atualizar dados!", "error", 3000);
                            return {};
                        }
                    });
                },
                insert: function(values) {
                    return $.ajax({
                        url: '/departamento/add-or-update-departamento',
                        method: 'POST',
                        contentType: 'application/json',
                        data: JSON.stringify(values), // Envia os valores do novo departamento
                        dataType: 'json'
                    }).then(response => {
                        if (!response.success) {
                            DevExpress.ui.notify(response.message, "error", 3000);
                        } else {
                            DevExpress.ui.notify(response.message, "success", 2000);
                        }
                        return response;
                    }).catch(error => {
                        if (error.responseJSON) {
                            DevExpress.ui.notify(error.responseJSON.message, "error", 3000);
                            return {};
                        } else {
                            DevExpress.ui.notify("Erro ao inserir dados!", "error", 3000);
                            return {};
                        }
                    });
                },
                remove: function(key) {
                    return $.ajax({
                        url: '/departamento/excluir-departamento', // Endpoint para excluir departamento
                        method: 'DELETE',
                        contentType: 'application/json',
                        data: JSON.stringify({ id: key }), // Envia o ID do departamento a ser excluído
                        dataType: 'json'
                    }).then(response => {
                        if (!response.success) {
                            DevExpress.ui.notify(response.message, "error", 3000);
                        } else {
                            DevExpress.ui.notify(response.message, "success", 2000);
                        }
                        return response;
                    }).catch(error => {
                        if (error.responseJSON) {
                            DevExpress.ui.notify(error.responseJSON.message, "error", 3000);
                            return {};
                        } else {
                            DevExpress.ui.notify("Erro ao excluir dados!", "error", 3000);
                            return {};
                        }
                    });
                }
            }),
            width: '100%',
            columnAutoWidth: true,
            keyExpr: 'ID', 
            showBorders: true,
            groupPanel: {
                visible: true,
            },
            grouping: {
                autoExpandAll: true // Impede que os grupos sejam expandidos automaticamente
            },
            toolbar: {
                items: [
                    {
                        name: "refresh",
                        location: "after",
                        widget: "dxButton",
                        options: {
                            icon: "refresh",
                            onClick: function() {
                                $("#gridContainer").dxDataGrid("instance").refresh();
                            },
                            text: "Atualizar"
                        }
                    },
                    {
                        name: "addRowButton",
                        location: "after",
                        widget: "dxButton",
                        options: {
                            icon: "plus",
                            onClick: function() {
                                $("#gridContainer").dxDataGrid("instance").addRow();
                            },
                            text: "Adicionar Departamento"
                        }
                    }
                ]
            },
            editing: {
                mode: 'batch',
                allowUpdating: true,
                allowAdding: true,
                allowDeleting: true,
                useIcons: true,
                texts: {
                    confirmDeleteMessage: "Tem certeza que deseja excluir este departamento? Esta ação não pode ser desfeita." 
                }
            },
            selection: {
                mode: 'multiple',
                showCheckBoxesMode: 'none'
            },
            hoverStateEnabled: true,
            pager: {
                visible: false
            },
            paging: false,
            headerFilter: {
                visible: true,
            },
            filterRow: {
                visible: true,
                applyFilter: 'auto',
            },
            export: {
                enabled: true,
                fileName: "Lista de Departamentos",
                allowExportSelectedData: false,
            },
            searchPanel: {
                visible: true,
                width: 240,
                placeholder: 'Procure...',
            },
            columns: [
                // {
                //     dataField: 'id',
                //     caption: 'ID',
                //     allowEditing: false, // Não permite edição do ID
                //     alignment: 'center', 
                //     width: 65,
                //     sortOrder: 'asc'
                // },
                {
                    dataField: 'nome_departamento',
                    caption: 'Nome Departamento',
                },
                {
                    dataField: 'id_gestor_departamento',
                    caption: 'Gestor Departamento',
                    width: 300,
                    lookup: {
                        dataSource: usuariosDataSource,
                        displayExpr: "nome",  
                        valueExpr: "id_gestor_departamento"
                    }
                },
                {
                    dataField: 'ativo',
                    caption: 'Ativo',
                    dataType: 'boolean',
                    alignment: 'center', 
                    width: 100
                }
            ],
            onRowUpdating: function(e) {
                e.newData = { ...e.oldData, ...e.newData };
            }
        });


        function getSelectBoxOptions(url, displayExpr, valueExpr, placeholder) {
            return {
                dataSource: new DevExpress.data.CustomStore({
                    loadMode: "raw",
                    load: function() {
                        return $.ajax({
                            url: url,
                            method: "GET",
                            dataType: "json"
                        }).then(response => {
                            if (response.success) {
                                return response.data;
                            } else {
                                DevExpress.ui.notify(response.message, "error", 3000);
                                return [];
                            }
                        }).catch(error => {
                            DevExpress.ui.notify("Erro ao buscar dados!", "error", 3000);
                            return [];
                        });
                    }
                }),
                displayExpr: displayExpr,
                valueExpr: valueExpr,
                placeholder: placeholder,
                searchEnabled: true,
                showClearButton: true,
            };
        }

    });
</script>
