
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Recursos Humanos</h1>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-12 mb-4">
            <!-- Approach -->
            <div class="card shadow mb-4">
                <div class="card-body">
                    <p>Apurações de Colaboradores</p>

                    <div id="form-container">
                        <div id="form-filtro"></div> <!-- Seu formulário aqui -->
                    </div>
                    <!-- Grid Container for the DataGrid -->
                    <div id="gridContainer"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->

<script>
    $(document).ready(function() {
        var dataGrid = null;
       
        // Inicializa o formulário
        const formInstance = $("#form-filtro").dxForm({
            formData: {},
            colCount: 1,
            items: [
                {
                    itemType: "group",
                    colCount: 2,
                    items: [
                        {
                            dataField: "dataInicial",
                            label: { visible: false },
                            editorType: "dxDateBox",
                            editorOptions: {
                                displayFormat: "dd/MM/yyyy", 
                                dateSerializationFormat: "yyyy-MM-dd",
                                placeholder: "Data Apuração Inicio",
                            },
                            validationRules: [{
                                type: 'required',
                                message: 'Data de Apuração é obrigatório.',
                            }],
                        },
                        {
                            dataField: "dataFinal",
                            label: { visible: false },
                            editorType: "dxDateBox",
                            editorOptions: {
                                displayFormat: "dd/MM/yyyy", 
                                dateSerializationFormat: "yyyy-MM-dd",
                                placeholder: "Data Apuração Fim",
                            },
                        },
                    ]
                },
                {
                    itemType: "group",
                    colCount: 2,
                    items: [
                        {
                            dataField: "colaborador",
                            editorType: "dxSelectBox",
                            label: { visible: false },
                            editorOptions: getSelectBoxOptions("/recursos-humanos/get-lookup-colaborador", "DSC", "ID", "Selecione o Colaborador")
                        },
                        {
                            dataField: "supervisor",
                            editorType: "dxSelectBox",
                            label: { visible: false },
                            editorOptions: getSelectBoxOptions("/recursos-humanos/get-lookup-supervisor", "DSC", "ID", "Selecione o Supervisor")
                        }
                    ]
                },
                {
                    itemType: "group",
                    colCount: 3,
                    items: [
                        {
                            dataField: "centroCusto",
                            editorType: "dxSelectBox",
                            label: { visible: false },
                            editorOptions: getSelectBoxOptions("/recursos-humanos/get-lookup-centro-custo", "DSC", "ID", "Selecione o Centro de Custo")
                        },
                        {
                            dataField: "escala",
                            editorType: "dxSelectBox",
                            label: { visible: false },
                            editorOptions: getSelectBoxOptions("/recursos-humanos/get-lookup-escala", "DSC", "ID", "Selecione a Escala")
                        },
                        {
                            dataField: "filial",
                            editorType: "dxSelectBox",
                            label: { visible: false },
                            editorOptions: getSelectBoxOptions("/recursos-humanos/get-lookup-filial", "DSC", "ID", "Selecione a Filial")
                        }
                    ]
                },
                {
                    itemType: "group",
                    colCount: 1,
                    items: [
                        {
                            dataField: "tipoApuracao",
                            editorType: "dxSelectBox",
                            label: { visible: false },
                            editorOptions: {
                                dataSource: [
                                    { ID: 1, DSC: "1 - Faltas" },
                                    { ID: 2, DSC: "2 - Intrajornada" },
                                    { ID: 3, DSC: "3 - Interjornada" },
                                    { ID: 4, DSC: "4 - Horas Extras (Acima de 2h)" },
                                    { ID: 5, DSC: "5 - Adicional Noturno" },
                                    { ID: 6, DSC: "6 - Trabalho em Folga" },
                                    { ID: 7, DSC: "7 - Trabalho em Feriado" },
                                    { ID: 8, DSC: "8 - Justificativa Marcação - Treinamento" },
                                    { ID: 9, DSC: "9 - Justificativa Marcação - Serviço Externo" },
                                    { ID: 10, DSC: "10 - Justificativa Marcação - Home Office" },
                                    { ID: 11, DSC: "11 - Justificativa Marcação - Registro Duplicado" },
                                    { ID: 12, DSC: "12 - Justificativa Marcação - Falha Equipamento" },
                                    { ID: 13, DSC: "13 - Justificativa Marcação - Esquecimento" },
                                ],
                                displayExpr: "DSC",
                                valueExpr: "ID",
                                placeholder: "Selecione o Tipo de Apuração",
                                searchEnabled: true,
                                showClearButton: true
                            }
                        }
                    ]
                },
                {
                    itemType: "button",
                    buttonOptions: {
                        text: "FILTRAR",
                        type: "success",
                        onClick: function() {
                            const formData = formInstance.option("formData");
                            // Chamar a função que atualiza a grid com os filtros
                            atualizarGrid(formData);
                        }
                    }
                }
            ]
        }).dxForm("instance");

        function getSelectBoxOptions(url, displayExpr, valueExpr, placeholder) {
            return {
                dataSource: new DevExpress.data.CustomStore({
                    loadMode: "raw",
                    load: function() {
                        return $.ajax({
                            url: url,
                            method: "GET",
                            dataType: "json"
                        }).then(response => {
                            if (response.success) {
                                return response.data;
                            } else {
                                DevExpress.ui.notify(response.message, "error", 3000);
                                return [];
                            }
                        }).catch(error => {
                            DevExpress.ui.notify("Erro ao buscar dados!", "error", 3000);
                            return [];
                        });
                    }
                }),
                displayExpr: displayExpr,
                valueExpr: valueExpr,
                placeholder: placeholder,
                searchEnabled: true
            };
        }

        // Função que será chamada ao clicar no botão FILTRAR
        function atualizarGrid(filtros) {
            console.log("Filtros aplicados:", filtros);
            
            dataGrid = $('#gridContainer').dxDataGrid({
                dataSource: new DevExpress.data.CustomStore({
                    key: 'ID', // Certifique-se de definir um campo único como chave
                    loadMode: "processed",
                    load: function(loadOptions) {
                        let params = {
                            ...filtros, // Seus filtros existentes
                            page: (loadOptions.skip / loadOptions.take) + 1, // Calcula a página atual
                            pageSize: loadOptions.take // Tamanho da página solicitado
                        };

                        // Adiciona parâmetros de ordenação se existirem
                        if (loadOptions.sort) {
                            params.sort = loadOptions.sort[0].selector;
                            params.sortOrder = loadOptions.sort[0].desc ? 'desc' : 'asc';
                        }

                        return $.ajax({
                            url: '/recursos-humanos/list-lancamentos-apuracoes-colaboradores',
                            method: 'GET',
                            dataType: 'json',
                            data: params, 
                        }).then(response => {
                            if (response.success) {
                                return {
                                    data: response.data,
                                    totalCount: response.totalCount 
                                };
                            } else {
                                DevExpress.ui.notify(response.message, "error", 3000);
                                return { data: [], totalCount: 0 };
                            }
                        }).catch(error => {
                            console.log('error', error);
                            if (error.responseJSON) {
                                DevExpress.ui.notify(error.responseJSON.message, "error", 3000);
                                return { data: [], totalCount: 0 };
                            } else {
                                DevExpress.ui.notify("Erro ao buscar dados!", "error", 3000);
                                return { data: [], totalCount: 0 };
                            }
                        });
                    }
                }),
                remoteOperations: {
                    paging: true,
                    filtering: true,
                    sorting: true,
                    grouping: true
                },
                height: 600,
                width: '100%',
                columnAutoWidth: true,
                elementAttr: {
                    class: "grid-personalizada"
                },
                showBorders: true,
                columnChooser: {
                    enabled: true,
                    mode: "dragAndDrop",
                    position: { 
                        my: "right", 
                        at: "right", 
                        of: ".dx-datagrid-column-chooser-button" 
                    }
                },
                groupPanel: {
                    visible: true,
                },
                toolbar: {
                    items: [
                        {
                            location: "after",
                            widget: "dxButton",
                            options: {
                                icon: "fa fa-expand",
                                text: "",
                                onClick: function () {
                                    var grid = $("#gridContainer").dxDataGrid("instance");
                                    grid.expandAll();
                                }
                            }
                        },
                        {
                            location: "after",
                            widget: "dxButton",
                            options: {
                                icon: "fa fa-compress",
                                text: "",
                                onClick: function () {
                                    var grid = $("#gridContainer").dxDataGrid("instance");
                                    grid.collapseAll();
                                }
                            }
                        },
                        {
                            name: "refresh",
                            location: "after",
                            widget: "dxButton",
                            options: {
                                icon: "refresh",
                                onClick: function() {
                                    $("#gridContainer").dxDataGrid("instance").refresh();
                                },
                                text: "Atualizar"
                            }
                        }
                    ]
                },
                editing: {
                    mode: 'batch',
                    allowUpdating: false,
                    allowDeleting: false,
                    useIcons: true,
                    selectTextOnEditStart: true,
                    startEditAction: 'click',
                    confirmDelete: true,
                    texts: {
                        confirmDeleteMessage: "Tem certeza que deseja remover esses lançamentos? É irreversível."
                    }
                },
                selection: {
                    mode: 'multiple',
                    showCheckBoxesMode: 'none'
                },
                hoverStateEnabled: true,
                pager: {
                    visible: true,
                    showPageSizeSelector: true,
                    allowedPageSizes: [500, 1000, 1500, 2000],
                    showInfo: true,
                    showNavigationButtons: true
                },
                paging: {
                    pageSize: 500
                },
                headerFilter: {
                    visible: true,
                },
                filterRow: {
                    visible: true,
                    applyFilter: 'auto',
                },
                export: {
                    enabled: true,
                    fileName: "Apurações Colaboradores",
                    allowExportSelectedData: false,
                },
                searchPanel: {
                    visible: true,
                    width: 240,
                    placeholder: 'Procure...',
                },
                columns: [
                    { dataField: 'CODEMP', caption: 'Empresa', allowEditing: false, alignment: 'center', width: 'auto' },
                    { dataField: 'NOMEMP', caption: 'Nome Empresa', allowEditing: false, alignment: 'left', width: 'auto' },
                    { dataField: 'FILRAT', caption: 'Filial', allowEditing: false, alignment: 'center', width: 'auto' },
                    { dataField: 'SIGFIL', caption: 'Nome Filial', allowEditing: false, alignment: 'left', width: 'auto' }
                    // Adicione suas outras colunas aqui
                ],
                summary: {
                    totalItems: [
                        // Exemplo de totalizador (descomente se necessário)
                        // {
                        //     column: "DEBITO", 
                        //     summaryType: "sum",
                        //     displayFormat: "Total: {0}",  
                        //     valueFormat: {
                        //         type: "currency",  
                        //         currency: "BRL" 
                        //     },
                        //     customizeText: function(cellInfo) {
                        //         if (cellInfo.value !== undefined && cellInfo.value !== null) {
                        //             return 'R$ ' + cellInfo.value.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
                        //         }
                        //         return '';
                        //     }
                        // },
                    ],
                    groupItems: [
                        // Exemplo de totalizador de grupo (descomente se necessário)
                        // {
                        //     column: 'DEBITO',
                        //     summaryType: 'sum',
                        //     valueFormat: 'currency',
                        //     displayFormat: 'Total: {0}',
                        //     showInGroupFooter: true,
                        //     valueFormat: {
                        //         type: "currency",  
                        //         currency: "BRL" 
                        //     },
                        //     customizeText: function(cellInfo) {
                        //         if (cellInfo.value !== undefined && cellInfo.value !== null) {
                        //             return 'R$ ' + cellInfo.value.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
                        //         }
                        //         return '';
                        //     }
                        // },
                    ],
                },
                onToolbarPreparing: function (e) {
                    var toolbarItems = e.toolbarOptions.items;
                    
                    toolbarItems.push({
                        location: "after",
                        widget: "dxButton",
                        options: {
                            icon: "fa fa-expand",
                            text: "",
                            onClick: function () {
                                var grid = e.component;
                                grid.expandAll();
                            }
                        }
                    });

                    toolbarItems.push({
                        location: "after",
                        widget: "dxButton",
                        options: {
                            icon: "fa fa-compress",
                            text: "",
                            onClick: function () {
                                var grid = e.component;
                                grid.collapseAll();
                            }
                        }
                    });

                    e.toolbarOptions.items.push({
                        name: "refresh",
                        location: "after",
                        widget: "dxButton",
                        options: {
                            icon: "refresh",
                            onClick: function() {
                                e.component.refresh();
                            },
                            text: "Atualizar" 
                        }
                    });
                }
            }).dxDataGrid('instance');
        }
    });


    // Função para formatar a data
    function formatarData(data) {
        const date = new Date(data);
        const dia = ('0' + date.getDate()).slice(-2);
        const mes = ('0' + (date.getMonth() + 1)).slice(-2);
        const ano = date.getFullYear();
        return `${dia}/${mes}/${ano}`;
    }    

</script>
