
<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Recursos Humanos</h1>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-12 mb-4">
            <!-- Approach -->
            <div class="card shadow mb-4">
                <div class="card-body">
                    <p>Apurações de Colaboradores</p>

                    <div id="form-container">
                        <div id="form-filtro"></div> <!-- Seu formulário aqui -->
                    </div>
                    <!-- Grid Container for the DataGrid -->
                    <div id="gridContainer"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->

<script>
    $(document).ready(function() {
        var dataGrid = null;
       
        // Inicializa o formulário
        const formInstance = $("#form-filtro").dxForm({
            formData: {},
            colCount: 1,
            items: [
                {
                    itemType: "group",
                    colCount: 1,
                    items: [{
                        dataField: "datReferencia",
                        label: { visible: false },
                        editorType: "dxDateBox",
                        editorOptions: {
                            displayFormat: "MM/yyyy",
                            dateSerializationFormat: "yyyy-MM-dd",
                            placeholder: "Mês/Ano Referência",
                            type: "date",
                            showClearButton: true,
                            calendarOptions: {
                                zoomLevel: "year",
                                maxZoomLevel: "year",
                                minZoomLevel: "month"
                            }
                        }
                    }]
                },
                {
                    itemType: "group",
                    colCount: 2,
                    items: [
                        {
                            dataField: "dataInicial",
                            label: { visible: false },
                            editorType: "dxDateBox",
                            editorOptions: {
                                displayFormat: "dd/MM/yyyy", 
                                dateSerializationFormat: "yyyy-MM-dd",
                                placeholder: "Data Apuração Inicio",
                                showClearButton: true,
                            }
                        },
                        {
                            dataField: "dataFinal",
                            label: { visible: false },
                            editorType: "dxDateBox",
                            editorOptions: {
                                displayFormat: "dd/MM/yyyy", 
                                dateSerializationFormat: "yyyy-MM-dd",
                                placeholder: "Data Apuração Fim",
                            },
                        },
                    ]
                },
                {
                    itemType: "group",
                    colCount: 2,
                    items: [
                        {
                            dataField: "colaborador",
                            editorType: "dxSelectBox",
                            label: { visible: false },
                            editorOptions: getSelectBoxOptions("/recursos-humanos/get-lookup-colaborador", "DSC", "ID", "Selecione o Colaborador")
                        },
                        {
                            dataField: "supervisor",
                            editorType: "dxSelectBox",
                            label: { visible: false },
                            editorOptions: getSelectBoxOptions("/recursos-humanos/get-lookup-supervisor", "DSC", "ID", "Selecione o Supervisor")
                        }
                    ]
                },
                {
                    itemType: "group",
                    colCount: 3,
                    items: [
                        {
                            dataField: "centroCusto",
                            editorType: "dxSelectBox",
                            label: { visible: false },
                            editorOptions: getSelectBoxOptions("/recursos-humanos/get-lookup-centro-custo", "DSC", "ID", "Selecione o Centro de Custo")
                        },
                        {
                            dataField: "escala",
                            editorType: "dxSelectBox",
                            label: { visible: false },
                            editorOptions: getSelectBoxOptions("/recursos-humanos/get-lookup-escala", "DSC", "ID", "Selecione a Escala")
                        },
                        {
                            dataField: "filial",
                            editorType: "dxSelectBox",
                            label: { visible: false },
                            editorOptions: getSelectBoxOptions("/recursos-humanos/get-lookup-filial", "DSC", "ID", "Selecione a Filial")
                        }
                    ]
                },
                {
                    itemType: "group",
                    colCount: 1,
                    items: [
                        {
                            dataField: "tipoApuracao",
                            editorType: "dxTagBox",
                            label: { visible: false },
                            editorOptions: {
                                dataSource: [
                                    { ID: 1, DSC: "1 - Faltas" },
                                    { ID: 2, DSC: "2 - Intrajornada" },
                                    { ID: 3, DSC: "3 - Interjornada" },
                                    { ID: 4, DSC: "4 - Horas Extras (Acima de 2h)" },
                                    { ID: 5, DSC: "5 - Adicional Noturno" },
                                    { ID: 6, DSC: "6 - Trabalho em Folga" },
                                    { ID: 7, DSC: "7 - Trabalho em Feriado" },
                                    { ID: 8, DSC: "8 - Justificativa Marcação - Treinamento" },
                                    { ID: 9, DSC: "9 - Justificativa Marcação - Serviço Externo" },
                                    { ID: 10, DSC: "10 - Justificativa Marcação - Home Office" },
                                    { ID: 11, DSC: "11 - Justificativa Marcação - Registro Duplicado" },
                                    { ID: 12, DSC: "12 - Justificativa Marcação - Falha Equipamento" },
                                    { ID: 13, DSC: "13 - Justificativa Marcação - Esquecimento" },
                                    { ID: 14, DSC: "14 - Compensação" },
                                    { ID: 15, DSC: "15 - Horas Extras 50%" },
                                    { ID: 16, DSC: "16 - Horas Extras 100%" },
                                ],
                                displayExpr: "DSC",
                                valueExpr: "ID",
                                placeholder: "Selecione o Tipo de Apuração",
                                searchEnabled: true,
                                showClearButton: true,
                                showSelectionControls: true,
                                applyValueMode: "useButtons",
                                selectAllText: "Selecionar todos", 
                                noDataText: "Nenhum dado disponível"
                            }, 
                            validationRules: [{
                                type: 'required',
                                message: 'Tipo de apuração é obrigatório.',
                            }],
                        }
                    ]
                },
                {
                    itemType: "button",
                    buttonOptions: {
                        text: "FILTRAR",
                        type: "success",
                        onClick: function() {
                             // Instância do formulário
                             var formInstance = $("#form-filtro").dxForm("instance");
                             var button = this; // Referência ao botão

                            // Validação do formulário
                            var validationResult = formInstance.validate();  // Valida o formulário

                            // Verifica se o formulário é válido
                            if (validationResult.isValid) {
                                // Desabilita o botão
                                button.option("disabled", true);
                                
                                // Opcional: Mostrar um indicador de carregamento
                                button.option("text", "Processando...");

                                // Se o formulário for válido, captura os dados
                                const formData = formInstance.option("formData");

                                // Chamar a função que atualiza a grid com os filtros
                                atualizarGrid(formData).finally(function() {
                                    // Reabilita o botão independente do resultado
                                    button.option("disabled", false);
                                    button.option("text", "FILTRAR");
                                });

                            } else {
                                // Se o formulário for inválido
                                DevExpress.ui.notify("Por favor, corrija os erros de validação.", "error", 3000);
                            }

                        }
                    }
                }
            ]
        }).dxForm("instance");

        function getSelectBoxOptions(url, displayExpr, valueExpr, placeholder) {
            return {
                dataSource: new DevExpress.data.CustomStore({
                    loadMode: "raw",
                    load: function() {
                        return $.ajax({
                            url: url,
                            method: "GET",
                            dataType: "json"
                        }).then(response => {
                            if (response.success) {
                                return response.data;
                            } else {
                                DevExpress.ui.notify(response.message, "error", 3000);
                                return [];
                            }
                        }).catch(error => {
                            DevExpress.ui.notify("Erro ao buscar dados!", "error", 3000);
                            return [];
                        });
                    }
                }),
                displayExpr: displayExpr,
                valueExpr: valueExpr,
                placeholder: placeholder,
                searchEnabled: true,
                showClearButton: true,
            };
        }

        // Função que será chamada ao clicar no botão FILTRAR
        function atualizarGrid(filtros) {
            // Destroi sempre a grid antes de inicia-la novamente.
            if (dataGrid != null) {
                if (dataGrid.instance) {
                    dataGrid.dispose();
                }
            }

            return new Promise((resolve, reject) => {
                dataGrid = $('#gridContainer').dxDataGrid({
                    dataSource: new DevExpress.data.CustomStore({
                        loadMode: "processed",
                        load: function(loadOptions) {
                            let params = filtros;

                            return $.ajax({
                                url: '/recursos-humanos/list-lancamentos-apuracoes-colaboradores',
                                method: 'GET',
                                dataType: 'json',
                                data: params, 
                            }).then(response => {
                                if (response.success) {
                                    resolve(); // Resolve a Promise quando a requisição for bem-sucedida
                                    return {
                                        data: response.data,
                                        totalCount: response.totalCount 
                                    };
                                } else {
                                    reject(); // Rejeita a Promise em caso de erro
                                    DevExpress.ui.notify(response.message, "error", 3000);
                                    return { data: [], totalCount: 0 };
                                }
                            }).catch(error => {
                                reject(); // Rejeita a Promise em caso de erro
                                console.log('error', error);
                                if (error.responseJSON) {
                                    DevExpress.ui.notify(error.responseJSON.message, "error", 3000);
                                    return { data: [], totalCount: 0 };
                                } else {
                                    DevExpress.ui.notify("Erro ao buscar dados!", "error", 3000);
                                    return { data: [], totalCount: 0 };
                                }
                            });
                        }
                    }),
                    height: 600,
                    width: '100%',
                    columnAutoWidth: true,
                    elementAttr: {
                        class: "grid-personalizada"
                    },
                    showBorders: true,
                    columnChooser: {
                        enabled: true,
                        mode: "dragAndDrop",
                        position: { 
                            my: "right", 
                            at: "right", 
                            of: ".dx-datagrid-column-chooser-button" 
                        }
                    },
                    groupPanel: {
                        visible: true,
                    },
                    toolbar: {
                        items: [
                            {
                                location: "after",
                                widget: "dxButton",
                                options: {
                                    icon: "fa fa-expand",
                                    text: "",
                                    onClick: function () {
                                        var grid = $("#gridContainer").dxDataGrid("instance");
                                        grid.expandAll();
                                    }
                                }
                            },
                            {
                                location: "after",
                                widget: "dxButton",
                                options: {
                                    icon: "fa fa-compress",
                                    text: "",
                                    onClick: function () {
                                        var grid = $("#gridContainer").dxDataGrid("instance");
                                        grid.collapseAll();
                                    }
                                }
                            },
                            {
                                name: "refresh",
                                location: "after",
                                widget: "dxButton",
                                options: {
                                    icon: "refresh",
                                    onClick: function() {
                                        $("#gridContainer").dxDataGrid("instance").refresh();
                                    },
                                    text: "Atualizar"
                                }
                            }
                        ]
                    },
                    editing: {
                        mode: 'batch',
                        allowUpdating: false,
                        allowDeleting: false,
                    },
                    selection: {
                        mode: 'multiple',
                        showCheckBoxesMode: 'none'
                    },
                    hoverStateEnabled: true,
                    pager: {
                        visible: true
                    },
                    paging: {
                        pageSize: 500
                    },
                    headerFilter: {
                        visible: true,
                    },
                    filterRow: {
                        visible: true,
                        applyFilter: 'auto',
                    },
                    export: {
                        enabled: true,
                        fileName: "Apurações Colaboradores",
                        allowExportSelectedData: false,
                        customizeExcelCell: function(options) {

                            // Verifica se é um cabeçalho (header)
                            if (options.gridCell.rowType === "header") {
                                // Mantém o texto original do cabeçalho
                                return;
                            }
                            // Formata as colunas de hora para o Excel
                            if (options.gridCell.column.dataField === 'QTD_HORAS_ADICIONAL_NOTURNO' || 
                                options.gridCell.column.dataField === 'QTD_HORAS_EXTRAS_50' || 
                                options.gridCell.column.dataField === 'QTD_HORAS_EXTRAS_100' ||
                                options.gridCell.column.dataField === 'JORNADA_REALIZADA_MINUTOS'
                            ) {
                                options.value = formatHourBalance(options.gridCell.value);
                                
                                // Configura o formato de hora no Excel (para que seja reconhecido como tempo)
                                options.numFmt = '[h]:mm:ss';
                            }
                        }
                    },
                    searchPanel: {
                        visible: true,
                        width: 240,
                        placeholder: 'Procure...',
                    },
                    columns: [
                        { dataField: 'NUMEMP', caption: 'Empresa', allowEditing: false, alignment: 'center', width: 80 },
                        { dataField: 'NOMEMP', caption: 'Nome Empresa', allowEditing: false, alignment: 'left', width: 'auto' },
                        { dataField: 'TIPCOL', caption: 'Tipo Colaborador', allowEditing: false, alignment: 'center', width: 70 },
                        { dataField: 'NUMCAD', caption: 'Matrícula', allowEditing: false, alignment: 'center', width: 80 },
                        { dataField: 'NOMFUN', caption: 'Colaborador', allowEditing: false, alignment: 'left', width: 'auto', sortIndex: 1, sortOrder: 'asc' },
                        { dataField: 'TITCAR', caption: 'Cargo', allowEditing: false, alignment: 'left', width: 'auto' },
                        { dataField: 'NOMLOC', caption: 'Local', allowEditing: false, alignment: 'left', width: 'auto' },
                        { dataField: 'CODCCU', caption: 'Centro de Custo', allowEditing: false, alignment: 'center', width: 120 },
                        { 
                            dataField: 'DATAPU_CONVERT', 
                            caption: 'Dt. Apuração', 
                            allowEditing: false, 
                            alignment: 'center', 
                            width: 100, 
                            dataType: 'date', 
                            format: 'dd/MM/yyyy',
                            editorOptions: {
                                displayFormat: 'dd/MM/yyyy'  
                            },
                            sortIndex: 2, sortOrder: 'asc'
                        },
                        { dataField: 'DIA_SEMANA', caption: 'Dia Semana', allowEditing: false, alignment: 'center', width: 'auto' },
                        { dataField: 'ESCALA_TROCA', caption: 'Escala Apuração', allowEditing: false, alignment: 'center', width: 'auto' },
                        { dataField: 'MARCACOES', caption: 'Horário Trabalhado', allowEditing: false, alignment: 'center', width: 'auto' },
                         {
                            dataField: 'JORNADA_REALIZADA_MINUTOS',
                            dataType: 'number',
                            format: {
                                type: 'custom',
                                formatter: formatHourBalance
                            },
                            alignment: 'center',
                            caption: 'Horas Trabalhadas',
                        },
                        { dataField: 'NOME_SUPERVISOR', caption: 'Supervisor Imediato', allowEditing: false, alignment: 'left', width: 'auto' },
                        {
                            dataField: 'QTD_HORAS_ADICIONAL_NOTURNO',
                            dataType: 'number',
                            alignment: 'center',
                            format: {
                                type: 'custom',
                                formatter: formatHourBalance
                            },
                            caption: 'Horas Adc. Noturno',
                            width: 120
                        },
                        {
                            dataField: 'QTD_HORAS_EXTRAS_50',
                            dataType: 'number',
                            alignment: 'center',
                            format: {
                                type: 'custom',
                                formatter: formatHourBalance
                            },
                            caption: 'HE 50%',
                            width: 120
                        },
                        {
                            dataField: 'QTD_HORAS_EXTRAS_100',
                            dataType: 'number',
                            alignment: 'center',
                            format: {
                                type: 'custom',
                                formatter: formatHourBalance
                            },
                            caption: 'HE 100%',
                            width: 120
                        },
                        { dataField: 'TIPO_COMPENSACAO', caption: 'Tipo Compensação', allowEditing: false, alignment: 'center', width: 150 },
                        { dataField: 'TIPO_APURACAO', caption: 'Tipo Apuração', allowEditing: false, alignment: 'center', width: 'auto', sortIndex: 3, sortOrder: 'asc' },
                        { dataField: 'DSC_SITUACAO_COLABORADOR', caption: 'Situação Colaborador', allowEditing: false, alignment: 'center', width: 150, visible: false },
                        { 
                            dataField: 'DATAFA', 
                            caption: 'Dt. Afastamento', 
                            allowEditing: false, 
                            alignment: 'center', 
                            width: 100, 
                            dataType: 'date', 
                            format: 'dd/MM/yyyy',
                            editorOptions: {
                                displayFormat: 'dd/MM/yyyy'  
                            }, 
                            visible: false
                        },
                    ],                
                    summary: {
                        totalItems: [
                            {
                                column: "TIPO_APURACAO", 
                                summaryType: "count",
                                displayFormat: "Total de Registros: {0}",
                                customizeText: function(cellInfo) {
                                    return cellInfo.value + " ocorrências";
                                }
                            },
                            // {
                            //     column: "JORNADA_REALIZADA_MINUTOS",
                            //     summaryType: "sum",
                            //     customizeText: function(cellInfo) {
                            //         return formatHourBalance(cellInfo.value);
                            //     }
                            // },
                            {
                                column: "QTD_HORAS_EXTRAS_50",
                                summaryType: "sum",
                                customizeText: function(cellInfo) {
                                    return formatHourBalance(cellInfo.value);
                                }
                            },
                            {
                                column: "QTD_HORAS_EXTRAS_100",
                                summaryType: "sum",
                                customizeText: function(cellInfo) {
                                    return formatHourBalance(cellInfo.value);
                                }
                            },
                            {
                                column: "QTD_HORAS_ADICIONAL_NOTURNO",
                                summaryType: "sum",
                                customizeText: function(cellInfo) {
                                    return formatHourBalance(cellInfo.value);
                                }
                            },
                        ],
                        groupItems: [
                            {
                                column: "TIPO_APURACAO", 
                                summaryType: "count",
                                displayFormat: "Total de Registros: {0}",
                                customizeText: function(cellInfo) {
                                    return cellInfo.value + " ocorrências";
                                }
                            },
                            // {
                            //     column: "JORNADA_REALIZADA_MINUTOS",
                            //     summaryType: "sum",
                            //     showInGroupFooter: false,
                            //     alignByColumn: true,
                            //     customizeText: function(cellInfo) {
                            //         return formatHourBalance(cellInfo.value);
                            //     }
                            // },
                            {
                                column: "QTD_HORAS_EXTRAS_50",
                                summaryType: "sum",
                                showInGroupFooter: false,
                                alignByColumn: true,
                                customizeText: function(cellInfo) {
                                    return formatHourBalance(cellInfo.value);
                                }
                            },
                            {
                                column: "QTD_HORAS_EXTRAS_100",
                                summaryType: "sum",
                                showInGroupFooter: false,
                                alignByColumn: true,
                                customizeText: function(cellInfo) {
                                    return formatHourBalance(cellInfo.value);
                                }
                            },
                            {
                                column: "QTD_HORAS_ADICIONAL_NOTURNO",
                                summaryType: "sum",
                                showInGroupFooter: false,
                                alignByColumn: true,
                                customizeText: function(cellInfo) {
                                    return formatHourBalance(cellInfo.value);
                                }
                            },
                        ],
                    },
                    onToolbarPreparing: function (e) {
                        var toolbarItems = e.toolbarOptions.items;
                        
                        toolbarItems.push({
                            location: "after",
                            widget: "dxButton",
                            options: {
                                icon: "fa fa-expand",
                                text: "",
                                onClick: function () {
                                    var grid = e.component;
                                    grid.expandAll();
                                }
                            }
                        });

                        toolbarItems.push({
                            location: "after",
                            widget: "dxButton",
                            options: {
                                icon: "fa fa-compress",
                                text: "",
                                onClick: function () {
                                    var grid = e.component;
                                    grid.collapseAll();
                                }
                            }
                        });

                        e.toolbarOptions.items.push({
                            name: "refresh",
                            location: "after",
                            widget: "dxButton",
                            options: {
                                icon: "refresh",
                                onClick: function() {
                                    e.component.refresh();
                                },
                                text: "Atualizar" 
                            }
                        });
                    }
                }).dxDataGrid('instance');
            });
        }
    });


    // Função para formatar a data
    function formatarData(data) {
        const date = new Date(data);
        const dia = ('0' + date.getDate()).slice(-2);
        const mes = ('0' + (date.getMonth() + 1)).slice(-2);
        const ano = date.getFullYear();
        return `${dia}/${mes}/${ano}`;
    } 
    
    function formatHourBalance(saldoHora) {
        if (!saldoHora && saldoHora !== 0) {
            return '00:00:00'; 
        }
        const saldo = saldoHora;
        const absSaldo = Math.abs(saldo);
        const hours = Math.floor(absSaldo / 60);
        const minutes = absSaldo % 60;
        
        const formattedHours = hours.toString().padStart(2, '0');
        const formattedMinutes = minutes.toString().padStart(2, '0');
        
        return (saldo < 0) 
            ? `-${formattedHours}:${formattedMinutes}:00` 
            : `${formattedHours}:${formattedMinutes}:00`;
    }

</script>
