<!-- Begin Page Content -->
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Recursos Humanos</h1>
    </div>
    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-12 mb-4">
            <!-- Approach -->
            <div class="card shadow mb-4">
                <div class="card-body">
                    <p>Banco Horas</p>

                    <div id="form-container">
                        <div id="form-filtro"></div> 
                    </div>
                    <!-- Grid Container for the DataGrid -->
                    <div id="gridContainer"></div>

                    <!-- Container for the Totals Grid - aligned to right -->
                    <div class="row mt-3">
                        <div class="col-md-3 offset-md-9">
                            <div id="gridTotalsContainer"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->

<script>
    $(document).ready(function() {
        var dataGrid = null;
        let totalsGrid = null;

        // Inicializa o formulário
        const formInstance = $("#form-filtro").dxForm({
            formData: {},
            colCount: 1,
            items: [
                {
                    itemType: "group",
                    colCount: 2,
                    items: [
                        {
                            dataField: "dataInicial",
                            label: { visible: false },
                            editorType: "dxDateBox",
                            editorOptions: {
                                displayFormat: "MM/yyyy",         
                                dateSerializationFormat: "yyyy-MM-dd", 
                                placeholder: "Mês/Ano inicial",
                                type: "date",                      
                                calendarOptions: {
                                    zoomLevel: "year", 
                                    maxZoomLevel: "year",
                                    minZoomLevel: "month",
                                }
                            },
                            validationRules: [{
                                type: 'required',
                                message: 'Período é obrigatório.',
                            }],
                        },
                        {
                            dataField: "dataFinal",
                            label: { visible: false },
                            editorType: "dxDateBox",
                            editorOptions: {
                                displayFormat: "MM/yyyy",
                                dateSerializationFormat: "yyyy-MM-dd",
                                placeholder: "Mês/Ano final",
                                type: "date",
                                calendarOptions: {
                                    zoomLevel: "year", 
                                    maxZoomLevel: "year",
                                    minZoomLevel: "month",
                                }
                            },
                        }
                    ]
                },
                {
                    itemType: "button",
                    buttonOptions: {
                        text: "FILTRAR",
                        type: "success",
                        onClick: function() {
                             // Instância do formulário
                             var formInstance = $("#form-filtro").dxForm("instance");
                             var button = this; // Referência ao botão

                            // Validação do formulário
                            var validationResult = formInstance.validate();  // Valida o formulário

                            // Verifica se o formulário é válido
                            if (validationResult.isValid) {
                                // Desabilita o botão
                                button.option("disabled", true);
                                
                                // Opcional: Mostrar um indicador de carregamento
                                button.option("text", "Processando...");

                                // Se o formulário for válido, captura os dados
                                const formData = formInstance.option("formData");

                                // Chamar a função que atualiza a grid com os filtros
                                atualizarGrid(formData).finally(function() {
                                    // Reabilita o botão independente do resultado
                                    button.option("disabled", false);
                                    button.option("text", "FILTRAR");
                                });

                            } else {
                                // Se o formulário for inválido
                                DevExpress.ui.notify("Por favor, corrija os erros de validação.", "error", 3000);
                            }

                        }
                    }
                }
            ]
        }).dxForm("instance");

        function getSelectBoxOptions(url, displayExpr, valueExpr, placeholder) {
            return {
                dataSource: new DevExpress.data.CustomStore({
                    loadMode: "raw",
                    load: function() {
                        return $.ajax({
                            url: url,
                            method: "GET",
                            dataType: "json"
                        }).then(response => {
                            if (response.success) {
                                return response.data;
                            } else {
                                DevExpress.ui.notify(response.message, "error", 3000);
                                return [];
                            }
                        }).catch(error => {
                            DevExpress.ui.notify("Erro ao buscar dados!", "error", 3000);
                            return [];
                        });
                    }
                }),
                displayExpr: displayExpr,
                valueExpr: valueExpr,
                placeholder: placeholder,
                searchEnabled: true,
                showClearButton: true,
            };
        }
        // Função que será chamada ao clicar no botão FILTRAR
        function atualizarGrid(filtros) {
            // Destroi sempre a grid antes de inicia-la novamente.
            if (dataGrid != null) {
                if (dataGrid.instance) {
                    dataGrid.dispose();
                }
            }
            if (totalsGrid != null && totalsGrid.instance) {
                totalsGrid.dispose();
            }
            return new Promise((resolve, reject) => {
                dataGrid = $('#gridContainer').dxDataGrid({
                    dataSource: new DevExpress.data.CustomStore({
                        loadMode: "processed",
                        load: function(loadOptions) {
                            let params = filtros;

                            return $.ajax({
                                url: '/recursos-humanos/list-banco-horas',
                                method: 'GET',
                                dataType: 'json',
                                data: params, 
                            }).then(response => {
                                if (response.success) {
                                    resolve(); // Resolve a Promise quando a requisição for bem-sucedida
                                    // Adiciona flag para linhas que devem ser incluídas no cálculo
                                    const processedData = response.data;

                                    // Agrupar os dados por NUMCAD, mantendo apenas o registro com a data mais recente (CMPLAN)
                                    const dataUnic = processedData.reduce((acc, current) => {
                                        // Se o NUMCAD já existe no acumulador
                                        if (acc[current.NUMCAD]) {
                                            // Compara as datas usando Moment.js (formato DD/MM/YY)
                                            const currentDate = moment(current.CMPLAN, 'DD/MM/YY');
                                            const existingDate = moment(acc[current.NUMCAD].CMPLAN, 'DD/MM/YY');
                                            
                                            // Mantém o registro com a data mais recente
                                            if (currentDate.isAfter(existingDate)) {
                                                acc[current.NUMCAD] = current;
                                            }
                                        } else {
                                            // Se o NUMCAD não existe, adiciona ao acumulador
                                            acc[current.NUMCAD] = current;
                                        }
                                        return acc;
                                    }, {});

                                    // 2. Extrair apenas os NUMCADs dos registros mais recentes
                                    const uniqueNumcads = Object.keys(dataUnic);

                                    // 3. Marcar todos os registros que estão no dataUnic
                                    const markedData = processedData.map(item => {
                                        const isMostRecent = item.NUMCAD in dataUnic && item.CMPLAN === dataUnic[item.NUMCAD].CMPLAN;
                                        return {
                                            ...item,
                                            SALDO_SUMMARY: isMostRecent ? item.SALDO : 0, 
                                            TOTAL_COLABORADOR_SUMMARY: isMostRecent ? 1 : 0,
                                            SALDO_POSIVO_SUMMARY: isMostRecent && item.SALDO > 0 ? 1 : 0,
                                            SALDO_NEGATIVO_SUMMARY: isMostRecent && item.SALDO < 0 ? 1 : 0,
                                            TOTAL_SALDO_POSITIVO_SUMMARY: isMostRecent ? item.SALDO_POSITIVO : 0, 
                                            TOTAL_SALDO_NEGATIVO_SUMMARY: isMostRecent ? item.SALDO_NEGATIVO : 0, 
                                            MEDIA_HORAS_DIA: item.SALDO < 0 ? Math.round(Math.abs(parseInt(item.SALDO)) / parseInt(item.DIAS_UTEIS_FECHAMENTO_PONTO)) : 0
                                        };
                                    });


                                    return {
                                        data: markedData, // Usar os dados marcados
                                        totalCount: response.totalCount 
                                    };
                                } else {
                                    reject(); // Rejeita a Promise em caso de erro
                                    DevExpress.ui.notify(response.message, "error", 3000);
                                    return { data: [], totalCount: 0 };
                                }
                            }).catch(error => {
                                reject(); // Rejeita a Promise em caso de erro
                                console.log('error', error);
                                if (error.responseJSON) {
                                    DevExpress.ui.notify(error.responseJSON.message, "error", 3000);
                                    return { data: [], totalCount: 0 };
                                } else {
                                    DevExpress.ui.notify("Erro ao buscar dados!", "error", 3000);
                                    return { data: [], totalCount: 0 };
                                }
                            });
                        }
                    }),
                    height: 600,
                    width: '100%',
                    columnAutoWidth: true,
                    elementAttr: {
                        class: "grid-personalizada"
                    },
                    showBorders: true,
                    columnChooser: {
                        enabled: true,
                        mode: "dragAndDrop",
                        position: { 
                            my: "right", 
                            at: "right", 
                            of: ".dx-datagrid-column-chooser-button" 
                        }
                    },
                    groupPanel: {
                        visible: true,
                    },
                    toolbar: {
                        items: [
                            {
                                location: "after",
                                widget: "dxButton",
                                options: {
                                    icon: "fa fa-expand",
                                    text: "",
                                    onClick: function () {
                                        var grid = $("#gridContainer").dxDataGrid("instance");
                                        grid.expandAll();
                                    }
                                }
                            },
                            {
                                location: "after",
                                widget: "dxButton",
                                options: {
                                    icon: "fa fa-compress",
                                    text: "",
                                    onClick: function () {
                                        var grid = $("#gridContainer").dxDataGrid("instance");
                                        grid.collapseAll();
                                    }
                                }
                            },
                            {
                                name: "refresh",
                                location: "after",
                                widget: "dxButton",
                                options: {
                                    icon: "refresh",
                                    onClick: function() {
                                        $("#gridContainer").dxDataGrid("instance").refresh();
                                    },
                                    text: "Atualizar"
                                }
                            }
                        ]
                    },
                    editing: {
                        mode: 'batch',
                        allowUpdating: false,
                        allowDeleting: false,
                    },
                    selection: {
                        mode: 'multiple',
                        showCheckBoxesMode: 'none'
                    },
                    hoverStateEnabled: true,
                    pager: {
                        visible: false
                    },
                    paging: {
                        pageSize: 500
                    },
                    headerFilter: {
                        visible: true,
                    },
                    filterRow: {
                        visible: true,
                        applyFilter: 'auto',
                    },
                    export: {
                        enabled: true,
                        fileName: "Saldo Banco de Horas",
                        allowExportSelectedData: false,
                        customizeExcelCell: function(options) {

                            // Verifica se é um cabeçalho (header)
                            if (options.gridCell.rowType === "header") {
                                // Mantém o texto original do cabeçalho
                                return;
                            }
                            // Formata as colunas de hora para o Excel
                            if (options.gridCell.column.dataField === 'SALDO' || options.gridCell.column.dataField === 'MEDIA_HORAS_DIA') {
                                options.value = formatHourBalance(options.gridCell.value);
                                
                                // Configura o formato de hora no Excel (para que seja reconhecido como tempo)
                                options.numFmt = '[h]:mm:ss';
                            }
                        }
                    },
                    searchPanel: {
                        visible: true,
                        width: 240,
                        placeholder: 'Procure...',
                    },
                    columns: [
                        { dataField: 'NUMEMP', caption: 'Empresa', allowEditing: false, alignment: 'center', width: 80 },
                        { dataField: 'NOMEMP', caption: 'Nome Empresa', allowEditing: false, alignment: 'left', width: 'auto' },
                        { dataField: 'CODFIL', caption: 'Filial', allowEditing: false, alignment: 'center', width: 80 },
                        { dataField: 'NOMFIL', caption: 'Nome Filial', allowEditing: false, alignment: 'left', width: 'auto' },
                        { dataField: 'CODCCU', caption: 'Centro de Custo', allowEditing: false, alignment: 'center', width: 'auto' },
                        { dataField: 'TIPCOL', caption: 'Tipo Colaborador', allowEditing: false, alignment: 'center', width: 70 },
                        { dataField: 'NUMCAD', caption: 'Matrícula', allowEditing: false, alignment: 'center', width: 80 },
                        { dataField: 'NOMFUN', caption: 'Colaborador', allowEditing: false, alignment: 'left', width: 'auto', sortIndex: 1, sortOrder: 'asc' },
                        { dataField: 'TITCAR', caption: 'Cargo', allowEditing: false, alignment: 'left', width: 'auto' },
                        { dataField: 'NOMLOC', caption: 'Local', allowEditing: false, alignment: 'left', width: 'auto' },
                        { dataField: 'MES_REFERENCIA', caption: 'Mês Referência', allowEditing: false, alignment: 'center', width: 120 },
                        { dataField: 'ANO_REFERENCIA', caption: 'Ano Referência', allowEditing: false, alignment: 'center', width: 120 },
                        {
                            dataField: 'SALDO',
                            dataType: 'number',
                            format: {
                                type: 'custom',
                                formatter: formatHourBalance
                            },
                            caption: 'Saldo Horas',
                            width: 200
                        },
                        {
                            dataField: 'SALDO_POSITIVO',
                            dataType: 'number',
                            format: {
                                type: 'custom',
                                formatter: formatHourBalance
                            },
                            caption: 'Saldo Horas (+)',
                            width: 200
                        },
                        {
                            dataField: 'SALDO_NEGATIVO',
                            dataType: 'number',
                            format: {
                                type: 'custom',
                                formatter: formatHourBalance
                            },
                            caption: 'Saldo Horas (-)',
                            width: 200
                        },
                        {
                            dataField: 'MEDIA_HORAS_DIA',
                            dataType: 'number',
                            format: {
                                type: 'custom',
                                formatter: formatHourBalance
                            },
                            caption: 'Compensação Média Diária',
                            width: 150
                        },
                        { dataField: 'NOME_SUPERVISOR', caption: 'Supervisor Imediato', allowEditing: false, alignment: 'left', width: 'auto' },
                    ],                
                    onToolbarPreparing: function (e) {
                        var toolbarItems = e.toolbarOptions.items;
                        
                        toolbarItems.push({
                            location: "after",
                            widget: "dxButton",
                            options: {
                                icon: "fa fa-expand",
                                text: "",
                                onClick: function () {
                                    var grid = e.component;
                                    grid.expandAll();
                                }
                            }
                        });

                        toolbarItems.push({
                            location: "after",
                            widget: "dxButton",
                            options: {
                                icon: "fa fa-compress",
                                text: "",
                                onClick: function () {
                                    var grid = e.component;
                                    grid.collapseAll();
                                }
                            }
                        });

                        e.toolbarOptions.items.push({
                            name: "refresh",
                            location: "after",
                            widget: "dxButton",
                            options: {
                                icon: "refresh",
                                onClick: function() {
                                    e.component.refresh();
                                },
                                text: "Atualizar" 
                            }
                        });
                    },
                    summary: {
                        totalItems: [
                            {
                                column: 'TOTAL_COLABORADOR_SUMMARY',
                                showInColumn: "SALDO",
                                summaryType: 'sum',
                                displayFormat: '{0}',
                                showInGroupFooter: true,
                                customizeText: function(cellInfo) {
                                    return 'Total de Colaboradores: ' + `${cellInfo.value}`
                                }, 
                            },
                            {
                                column: 'SALDO_POSIVO_SUMMARY',
                                showInColumn: "SALDO",
                                summaryType: 'sum',
                                displayFormat: '{0}',
                                showInGroupFooter: true,
                                customizeText: function(cellInfo) {
                                    return 'Com Saldo Positivo: ' + `${cellInfo.value}`
                                }, 
                            },
                            {
                                column: 'SALDO_NEGATIVO_SUMMARY',
                                showInColumn: "SALDO",
                                summaryType: 'sum',
                                displayFormat: '{0}',
                                showInGroupFooter: true,
                                customizeText: function(cellInfo) {
                                    return 'Com Saldo Negativo: ' + `${cellInfo.value}`
                                }, 
                            },
                            {
                                column: 'SALDO_SUMMARY',
                                showInColumn: "SALDO",
                                summaryType: 'sum',
                                displayFormat: '{0}',
                                showInGroupFooter: true,
                                customizeText: function(cellInfo) {
                                    if (!cellInfo.value && cellInfo.value !== 0) {
                                        return '00:00:00'; 
                                    }
                                    const saldo = cellInfo.value;
                                    const absSaldo = Math.abs(saldo);
                                    const hours = Math.floor(absSaldo / 60);
                                    const minutes = absSaldo % 60;
                                    
                                    const formattedHours = hours.toString().padStart(2, '0');
                                    const formattedMinutes = minutes.toString().padStart(2, '0');
                                    
                                    return (saldo < 0) ?  'Saldo Total: ' + `-${formattedHours}:${formattedMinutes}:00` : 'Saldo Total: ' + `${formattedHours}:${formattedMinutes}:00`;
                                }, 
                            },
                            {
                                column: 'TOTAL_SALDO_POSITIVO_SUMMARY',
                                showInColumn: "SALDO",
                                summaryType: 'sum',
                                displayFormat: '{0}',
                                showInGroupFooter: true,
                                customizeText: function(cellInfo) {
                                    if (!cellInfo.value && cellInfo.value !== 0) {
                                        return '00:00:00'; 
                                    }
                                    const saldo = cellInfo.value;
                                    const absSaldo = Math.abs(saldo);
                                    const hours = Math.floor(absSaldo / 60);
                                    const minutes = absSaldo % 60;
                                    
                                    const formattedHours = hours.toString().padStart(2, '0');
                                    const formattedMinutes = minutes.toString().padStart(2, '0');
                                    
                                    return (saldo < 0) ?  'Saldo Total (+): ' + `-${formattedHours}:${formattedMinutes}:00` : 'Saldo Total (+): ' + `${formattedHours}:${formattedMinutes}:00`;
                                }, 
                            },
                            {
                                column: 'TOTAL_SALDO_NEGATIVO_SUMMARY',
                                showInColumn: "SALDO",
                                summaryType: 'sum',
                                displayFormat: '{0}',
                                showInGroupFooter: true,
                                customizeText: function(cellInfo) {
                                    if (!cellInfo.value && cellInfo.value !== 0) {
                                        return '00:00:00'; 
                                    }
                                    const saldo = cellInfo.value;
                                    const absSaldo = Math.abs(saldo);
                                    const hours = Math.floor(absSaldo / 60);
                                    const minutes = absSaldo % 60;
                                    
                                    const formattedHours = hours.toString().padStart(2, '0');
                                    const formattedMinutes = minutes.toString().padStart(2, '0');
                                    
                                    return (saldo < 0) ?  'Saldo Total (-): ' + `-${formattedHours}:${formattedMinutes}:00` : 'Saldo Total (-): ' + `${formattedHours}:${formattedMinutes}:00`;
                                }, 
                            },
                        ],
                        groupItems: [
                            {
                                column: 'TOTAL_COLABORADOR_SUMMARY',
                                showInColumn: "SALDO",
                                summaryType: 'sum',
                                displayFormat: '{0}',
                                showInGroupFooter: true,
                                customizeText: function(cellInfo) {
                                    return 'Total de Colaboradores: ' + `${cellInfo.value}`
                                }, 
                            },
                            {
                                column: 'SALDO_POSIVO_SUMMARY',
                                showInColumn: "SALDO",
                                summaryType: 'sum',
                                displayFormat: '{0}',
                                showInGroupFooter: true,
                                customizeText: function(cellInfo) {
                                    return 'Com Saldo Positivo: ' + `${cellInfo.value}`
                                }, 
                            },
                            {
                                column: 'SALDO_NEGATIVO_SUMMARY',
                                showInColumn: "SALDO",
                                summaryType: 'sum',
                                displayFormat: '{0}',
                                showInGroupFooter: true,
                                customizeText: function(cellInfo) {
                                    return 'Com Saldo Negativo: ' + `${cellInfo.value}`
                                }, 
                            },
                            {
                                column: 'SALDO_SUMMARY',
                                showInColumn: "SALDO",
                                summaryType: 'sum',
                                displayFormat: '{0}',
                                showInGroupFooter: true,
                                customizeText: function(cellInfo) {
                                    if (!cellInfo.value && cellInfo.value !== 0) {
                                        return '00:00:00'; 
                                    }
                                    const saldo = cellInfo.value;
                                    const absSaldo = Math.abs(saldo);
                                    const hours = Math.floor(absSaldo / 60);
                                    const minutes = absSaldo % 60;
                                    
                                    const formattedHours = hours.toString().padStart(2, '0');
                                    const formattedMinutes = minutes.toString().padStart(2, '0');
                                    
                                    return (saldo < 0) ? 'Saldo Total: ' + `-${formattedHours}:${formattedMinutes}:00` : 'Saldo Total: ' + `${formattedHours}:${formattedMinutes}:00`;
                                }, 
                            },
                            {
                                column: 'TOTAL_SALDO_POSITIVO_SUMMARY',
                                showInColumn: "SALDO",
                                summaryType: 'sum',
                                displayFormat: '{0}',
                                showInGroupFooter: true,
                                customizeText: function(cellInfo) {
                                    if (!cellInfo.value && cellInfo.value !== 0) {
                                        return '00:00:00'; 
                                    }
                                    const saldo = cellInfo.value;
                                    const absSaldo = Math.abs(saldo);
                                    const hours = Math.floor(absSaldo / 60);
                                    const minutes = absSaldo % 60;
                                    
                                    const formattedHours = hours.toString().padStart(2, '0');
                                    const formattedMinutes = minutes.toString().padStart(2, '0');
                                    
                                    return (saldo < 0) ?  'Saldo Total (+): ' + `-${formattedHours}:${formattedMinutes}:00` : 'Saldo Total (+): ' + `${formattedHours}:${formattedMinutes}:00`;
                                }, 
                            },
                            {
                                column: 'TOTAL_SALDO_NEGATIVO_SUMMARY',
                                showInColumn: "SALDO",
                                summaryType: 'sum',
                                displayFormat: '{0}',
                                showInGroupFooter: true,
                                customizeText: function(cellInfo) {
                                    if (!cellInfo.value && cellInfo.value !== 0) {
                                        return '00:00:00'; 
                                    }
                                    const saldo = cellInfo.value;
                                    const absSaldo = Math.abs(saldo);
                                    const hours = Math.floor(absSaldo / 60);
                                    const minutes = absSaldo % 60;
                                    
                                    const formattedHours = hours.toString().padStart(2, '0');
                                    const formattedMinutes = minutes.toString().padStart(2, '0');
                                    
                                    return (saldo < 0) ?  'Saldo Total (-): ' + `-${formattedHours}:${formattedMinutes}:00` : 'Saldo Total (-): ' + `${formattedHours}:${formattedMinutes}:00`;
                                }, 
                            },
                        ],
                    },
                }).dxDataGrid('instance');
            });
        }
        function formatHourBalance(saldoHora) {
            if (!saldoHora && saldoHora !== 0) {
                return '00:00:00'; 
            }
            const saldo = saldoHora;
            const absSaldo = Math.abs(saldo);
            const hours = Math.floor(absSaldo / 60);
            const minutes = absSaldo % 60;
            
            const formattedHours = hours.toString().padStart(2, '0');
            const formattedMinutes = minutes.toString().padStart(2, '0');
            
            return (saldo < 0) 
                ? `-${formattedHours}:${formattedMinutes}:00` 
                : `${formattedHours}:${formattedMinutes}:00`;
        }
    });

    // Função para formatar a data
    function formatarData(data) {
        const date = new Date(data);
        const dia = ('0' + date.getDate()).slice(-2);
        const mes = ('0' + (date.getMonth() + 1)).slice(-2);
        const ano = date.getFullYear();
        return `${dia}/${mes}/${ano}`;
    }    
</script>
